### ISSUE TITLE
Rename sponsor model to Sponsor

### ISSUE THREAD

**Issue by ghoshbishakh** [NIT-dgp/festcms#102]
Change this line https://github.com/NIT-dgp/festcms/blob/master/festflow/models.py#L138
From 'sponsor' to 'Sponsor'

Then run `python manage.py makemigrations`

**Comment by nkprince007** [comment]
`organizerMember`needs rework too, I guess?
https://github.com/NIT-dgp/festcms/blob/master/festflow/models.py#L115 !?

**Comment by ghoshbishakh** [comment]
@nkprince007 yes add the issue

**Comment by ankan17** [comment]
I would like to work on this issue..

**Comment by ghoshbishakh** [comment]
@ankan17 go ahead!
