### ISSUE TITLE
Navbar Design

### ISSUE THREAD

**Issue by ghoshbishakh** [NIT-dgp/festcms#12]

**Comment by ghoshbishakh** [comment]
related to #6

**Comment by ghoshbishakh** [comment]
Let us have a discussion here @rahilsmd @ananyo2012 

I want a simple multipage site as it is now. Just let the navbar be uniform.

**Comment by ananyo2012** [comment]
Yes sure we can have a discussion. @ghoshbishakh Can you suggest some navbar designs. You can post some links to pages or screenshots.

**Comment by ghoshbishakh** [comment]
@ananyo2012 I do not want it to be super complicated like how it is now. Anything uniform with proper fonts and color will do for me maintaining responsive design.

**Comment by ghoshbishakh** [comment]
closing as ank related frontend design is no longer a valid issue here
