### ISSUE TITLE
Proper license is needed

### ISSUE THREAD

**Issue by ghoshbishakh** [NIT-dgp/festcms#123]
Our options are GNU GPL
MIT
Apache

**Comment by nkprince007** [comment]
GPL 3.0 is fine, I guess. Or we could go with MIT too.

**Comment by ghoshbishakh** [comment]
Lets go with MIT

**Comment by nkprince007** [comment]
Okay you can just add it online from GitHub page itself. 
		

		Sent from Outlook for iOS
	





On Tue, May 23, 2017 at 5:13 PM +0530, "Bishakh Ghosh" <notifications@github.com> wrote:












Lets go with MIT
