### ISSUE TITLE
Design the index page as a landing page

### ISSUE THREAD

**Issue by ghoshbishakh** [NIT-dgp/festcms#3]
Make a beautiful landing page.

**Comment by ghoshbishakh** [comment]
@rahilsmd please work on this.

**Comment by ghoshbishakh** [comment]
@rahilsmd I am working on it

**Comment by ananyo2012** [comment]
In the landing page change the HH:MM:SS format to HH days MM minutes and SS seconds. You can use a distinctive font or the timer.

**Comment by ghoshbishakh** [comment]
closing as ank related frontend design is no longer a valid issue here
