### ISSUE TITLE
Design a generic frontend

### ISSUE THREAD

**Issue by ghoshbishakh** [NIT-dgp/festcms#33]
Preferably with theming support of some kind.

**Comment by akshatnitd** [comment]
@ghoshbishakh Can you brief me about how to go about it? :stuck_out_tongue:

**Comment by akshatnitd** [comment]
@ghoshbishakh What are the things to be added? :smile:

**Comment by ghoshbishakh** [comment]
@akshatnitd I want it to support some kind of themes. You can try to figure out how to do that. Or wait for some times I will be gradually posting smaller issues related to this one.

**Comment by akshatnitd** [comment]
@ghoshbishakh Okay! :smile:

**Comment by ghoshbishakh** [comment]
@nkprince007 Do you have any suggestions for theme support?

**Comment by nkprince007** [comment]
@ghoshbishakh  Actually, I prefer using [Foundation](http://foundation.zurb.com/) with [Materialize CSS](materializecss.com) for theming. Or if you'd like to use bootstrap, [materialdesign bootstrap](http://fezvrasta.github.io/bootstrap-material-design/) could work

**Comment by ghoshbishakh** [comment]
@nkprince007 the css framework is not the issue. My issue is how to allow users to change themes conveniently?

**Comment by nkprince007** [comment]
Oh.. sorry, then I suppose, we could use different templates for each theme, if layout needs to change.

**Comment by ghoshbishakh** [comment]
Well have you seen wordpress? They have a nice way of applying themes. So can we provide such theme support here?

**Comment by nkprince007** [comment]
Yeah, I think we can, as specified in [django-theming](https://pypi.python.org/pypi/django-theming/1.0) package.

**Comment by ghoshbishakh** [comment]
@nkprince007 that repo is 2 years old. But still we can investigate. Take some time in finding the alternatices.
If we donot find anything suitable we are going to build our own theming engine.

**Comment by nkprince007** [comment]
Ok, bro.

**Comment by nkprince007** [comment]
I've been unable to find reliable sources. IMO, we should start building it on our own. 

Here's one such lead:
- https://github.com/f4nt/django-yaba

**Comment by ghoshbishakh** [comment]
@nkprince007 look at this one http://stackoverflow.com/questions/2462792/load-django-template-from-the-database

**Comment by ghoshbishakh** [comment]
@nkprince007 also https://github.com/jazzband/django-dbtemplates/
