### ISSUE TITLE
Sponsor name not appearing in admin panel

### ISSUE THREAD

**Issue by ghoshbishakh** [NIT-dgp/festcms#39]
![screenshot from 2016-11-15 01-52-54](https://cloud.githubusercontent.com/assets/5156787/20281612/0bbf6b6e-aad7-11e6-88a2-751473c1a934.png)

Sponsor name should be displayed in admin panel instead of "Sponsor Object"

Change the Sponsor model  in [models.py](https://github.com/NIT-dgp/festcms/blob/master/festflow/models.py#L95) file to include a `__str__` method  like in other models.

### Steps to reproduce:
Go to http://localhost:8000/admin/ page
Login as admin
Go to [sponsors](http://127.0.0.1:8000/admin/festflow/sponsor/) page.

### Steps to fix:
In models file of festflow add a `__str__` method to return the sponsor's name:

```
def __str__(self):
        return self.name
```

**Comment by nkprince007** [comment]
Closed via 0244adac5c253c5ce8e9655cf75a6239201e12cb
