### ISSUE TITLE
Event view page: Display title of event in title of the page

### ISSUE THREAD

**Issue by ghoshbishakh** [NIT-dgp/festcms#42]
In [event_view](https://github.com/NIT-dgp/festcms/blob/master/festflow/templates/festflow/event_view.html) template, currently "Event View" is diaplayed for every event.
This should be changed to display the name of the event.

### Steps to fix:
In [event_view template of festflow](https://github.com/NIT-dgp/festcms/blob/master/festflow/templates/festflow/event_view.html):
Change
```
<title>Event View</title>
```
To
```
<title>{{ event.name }}</title>
```

**Comment by akshatnitd** [comment]
PR for this has been made.

**Comment by ghoshbishakh** [comment]
@akshatnitd yes now get it merged :wink:

**Comment by ghoshbishakh** [comment]
Closed through #43

**Comment by akshatnitd** [comment]
:smiley:
