### ISSUE TITLE
Unable to open the event description when logged on from admin profile

### ISSUE THREAD

**Issue by akshatnitd** [NIT-dgp/festcms#44]
The admin profile has to be logged out before viewing the event description of each event, or else an error is displayed.

**Comment by ghoshbishakh** [comment]
@akshatnitd thanks for reporting! Will you try to solve the issue yourself?

**Comment by akshatnitd** [comment]
@ghoshbishakh Yes, I ll giving it a try :smile:

**Comment by ghoshbishakh** [comment]
# Steps to reproduce the issue:

1. Create a superuser using `python manage.py createsuperuser`
2. Create a new Event
3. Do not log out from admin panel
5. Open events page that is /events
6. Click on the event

![screenshot from 2016-11-19 12-24-18](https://cloud.githubusercontent.com/assets/5156787/20453695/1b05bd7e-ae53-11e6-8702-a05f7b353b18.png)
