### ISSUE TITLE
Create a new model for Talks or Keynotes etc.

### ISSUE THREAD

**Issue by ghoshbishakh** [NIT-dgp/festcms#48]
There should be a model for talks that are a specitl type of event which requires name of the guest giving the talk. This model can extend the existing Event model.

**Comment by abhsag24** [comment]
do star nights go into this as well? :P

**Comment by nkprince007** [comment]
Extending the `Event` model seems a fair idea, but also gives some fields like `problem_statement_file`, `logo` etc., which don't seem to be relevant here. I'd like to hear some more insight into the fields. :smile:

**Comment by nkprince007** [comment]
Closing this as it's already implemented in 459c700
