### ISSUE TITLE
Admin: add a WYSIWYG editor for editing about section in admin panel

### ISSUE THREAD

**Issue by ghoshbishakh** [NIT-dgp/festcms#63]

**Comment by nkprince007** [comment]
Is [this](http://www.w3schools.com/css/tryit.asp?filename=trycss_default) what you're suggesting @ghoshbishakh

**Comment by ghoshbishakh** [comment]
@nkprince007 yes that is a WYSIWYG editor. But keep in mind that the libraries you plan to use must be open source.

**Comment by nkprince007** [comment]
Ok @ghoshbishakh, then I think a django variant of [this](http://ckeditor.com/) is fine, I guess?

**Comment by ghoshbishakh** [comment]
@nkprince007 can you make a list of options available and we can have a discussion? (CKeditor is a bit heavy)

**Comment by ghoshbishakh** [comment]
Well I found the list:
https://djangopackages.org/grids/g/wysiwyg/

**Comment by ghoshbishakh** [comment]
@nkprince007 looks like CKeditor is the one. Green flag from me! Go ahead and implement it. Do it in a separate branch with some documentation (code comments)! :+1:

**Comment by nkprince007** [comment]
:) Ok..

**Comment by ananyo2012** [comment]
Is this issue related only to add the library or add the editor field too?

**Comment by ghoshbishakh** [comment]
@ananyo2012 editor field too
