### ISSUE TITLE
Feedback: Add a section to collect feedback from users

### ISSUE THREAD

**Issue by nkprince007** [NIT-dgp/festcms#67]

**Comment by nkprince007** [comment]
@ghoshbishakh could you please elaborate on the fields that we'd like to have here?

**Comment by ghoshbishakh** [comment]
@nkprince007 ideally we would want custom forms. I dont know if it is possible in some way. Is it possible?

**Comment by nkprince007** [comment]
@ghoshbishakh Do you mean something like google forms?

**Comment by ghoshbishakh** [comment]
@nkprince007 yes something like that. I do not think that will be trivial. More thinking is needed.

**Comment by nkprince007** [comment]
How about [these](https://djangopackages.org/grids/g/form-builder/)? I think [django-forms-builder](https://github.com/stephenmcd/django-forms-builder) or [django-fobi](https://github.com/barseghyanartur/django-fobi) might be our gig, what do you feel @ghoshbishakh?

**Comment by ghoshbishakh** [comment]
@nkprince007 looks promising but I need to investigate more. I have to see their implementation.

**Comment by nkprince007** [comment]
@ghoshbishakh any progress?

**Comment by ghoshbishakh** [comment]
@nkprince007 django-forms-builder looks good but I don't understand how it is working. You can go ahead and use though as it seems to fulfill the requirement.

**Comment by nkprince007** [comment]
```
Django==1.10.4
django-email-extras==0.3.3
django-form-builder==0.13.0
future==0.15.0
Unidecode==0.4.19
sphinx-me==0.3
python-gnupg==0.3.9
```
Seems to have quite a list of requirements, @ghoshbishakh 
Even tries to update django version.

**Comment by ghoshbishakh** [comment]
@nkprince007 why would it update django? are you sure?

**Comment by ghoshbishakh** [comment]
No I saw the setup.py. It says Django >= 1.8

**Comment by nkprince007** [comment]
```
(festcms-venv) festcms [feedback] % pip install -U django-forms-builder
Collecting django-forms-builder
  Downloading django_forms_builder-0.13.0-py2.py3-none-any.whl (99kB)
    100% |████████████████████████████████| 102kB 102kB/s 
Collecting unidecode (from django-forms-builder)
  Downloading Unidecode-0.04.19.tar.gz (204kB)
    100% |████████████████████████████████| 204kB 205kB/s 
Collecting django<1.11,>=1.8 (from django-forms-builder)
  Using cached Django-1.10.4-py2.py3-none-any.whl
Collecting sphinx-me>=0.1.2 (from django-forms-builder)
  Downloading sphinx_me-0.3-py2.py3-none-any.whl
Collecting future<=0.15.0 (from django-forms-builder)
  Downloading future-0.15.0.tar.gz (810kB)
    100% |████████████████████████████████| 819kB 218kB/s 
Collecting django-email-extras>=0.2 (from django-forms-builder)
  Downloading django_email_extras-0.3.3-py2.py3-none-any.whl
Collecting python-gnupg (from django-email-extras>=0.2->django-forms-builder)
  Downloading python_gnupg-0.3.9-py2.py3-none-any.whl
Building wheels for collected packages: unidecode, future
  Running setup.py bdist_wheel for unidecode ... done
  Stored in directory: /home/nkprince007/.cache/pip/wheels/72/da/8f/64e7de75111e143339d331011b56b3a8186e2eb07b0b5e383b
  Running setup.py bdist_wheel for future ... done
  Stored in directory: /home/nkprince007/.cache/pip/wheels/2c/5d/b4/e10dcfb2166be9a43b1a289b874b5e8da34e01cd61e3bad4ed
Successfully built unidecode future
Installing collected packages: unidecode, django, sphinx-me, future, python-gnupg, django-email-extras, django-forms-builder
  Found existing installation: Django 1.8
    Uninstalling Django-1.8:
      Successfully uninstalled Django-1.8
  Installing from a newer Wheel-Version (1.1)
Successfully installed django-1.10.4 django-email-extras-0.3.3 django-forms-builder-0.13.0 future-0.15.0 python-gnupg-0.3.9 sphinx-me-0.3 unidecode-0.4.19
```

**Comment by ghoshbishakh** [comment]
@nkprince007 well I don't know why it is updating stuff.

**Comment by nkprince007** [comment]
Maybe we could avoid it by placing `django-forms-builder` requirement above `Django` and make it put back `1.8` ?

**Comment by ghoshbishakh** [comment]
@nkprince007 oye.. you are doing it with -U. Please clean up your virtualenv and redo the requirements.txt installation and try `pip install django-forms-builder`

**Comment by nkprince007** [comment]
@ghoshbishakh Yup, did it. Works fine.

**Comment by ghoshbishakh** [comment]
@nkprince007 solved the problem?

**Comment by nkprince007** [comment]
Yup. @ghoshbishakh

**Comment by nkprince007** [comment]
BTW, [django-forms-builder](https://github.com/stephenmcd/django-forms-builder) has lot of configuration, that could be done. Do we add it to `README.md` or maybe add some link to their [README](https://github.com/stephenmcd/django-forms-builder/blob/master/README.rst) ? It's quite a lot of configuration.

**Comment by ghoshbishakh** [comment]
@nkprince007 sure do that thanks!

**Comment by ghoshbishakh** [comment]
@nkprince007 Do what you think will be better!

**Comment by nkprince007** [comment]
I think it's better leaving that to those guys, cuz it could update sooner or later. @ghoshbishakh

**Comment by nkprince007** [comment]
And since we're using `django-email-extras` anyway, I'll update our way of sending mails, too. @ghoshbishakh.

**Comment by ghoshbishakh** [comment]
@nkprince007 sounds good

**Comment by nkprince007** [comment]
@ghoshbishakh `django-forms-builder` is good. I've messed around a bit. But, all the forms created have the pattern `r'^forms/``. It gives us just the ability to add to it, like `forms/feedback` etc.

**Comment by ghoshbishakh** [comment]
@nkprince007 forms/feedback is also fine

**Comment by ghoshbishakh** [comment]
@nkprince007 good! iopen the issue you wanted. That is changing the mail backend to something right?

**Comment by nkprince007** [comment]
Sure.
