### ISSUE TITLE
Custom navbar entries

### ISSUE THREAD

**Issue by ghoshbishakh** [NIT-dgp/festcms#71]
Add a model for navbar entries and build a custom templatetag to display a navbar with those entries

**Comment by nkprince007** [comment]
```
{% load navbar %}
...
<body>
{% navbar %}
</body>
```
Something of this sort? Looks okay but most of the html moves into python file, which shouldn't be something acceptable. Maybe make a template and render it with the data from model and then push it back?

**Comment by nkprince007** [comment]
BTW, I've missed something in the last migrations for FAQ, related to Meta class, So, perhaps add an issue?

**Comment by ghoshbishakh** [comment]
@nkprince007 punch that in in your last PR.
