### ISSUE TITLE
Design various pages

### ISSUE THREAD

**Issue by ananyo2012** [NIT-dgp/festcms#8]
I am listing all design related issues here. Close this after each one is fixed
- [ ] Redesign **About Us** page
- [ ] Redesign **Events** Page
- [ ] Redesign **Sponsors** page
- [ ] Redesign **Contacts** page
- [ ] Redesign **Login** page

Possible design solutions can be discussed with issues before designing a page.

**Comment by ananyo2012** [comment]
@ghoshbishakh You can label all design related issues with a design label

**Comment by ghoshbishakh** [comment]
closing as ank related frontend design is no longer a valid issue here
